# Generated by Django 3.0.2 on 2020-01-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200117_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_child_of',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_grand_child_of',
        ),
    ]
