# Generated by Django 3.0.2 on 2020-01-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200120_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_child_of',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_grand_child_of',
        ),
    ]
