# Generated by Django 3.0.2 on 2020-01-29 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2020, 1, 29, 17, 10, 18, 770242)),
        ),
    ]
