# Generated by Django 3.0.5 on 2020-08-14 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200307_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2020, 8, 14, 9, 16, 48, 924761)),
        ),
    ]
