# Generated by Django 3.0.5 on 2020-08-16 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200814_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2020, 8, 16, 18, 17, 32, 747187)),
        ),
    ]
