# Generated by Django 3.0.2 on 2020-01-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('whatsapp', models.URLField()),
            ],
        ),
    ]
