# Generated by Django 3.0.2 on 2020-01-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200123_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallinks',
            name='name',
        ),
    ]
