# Generated by Django 3.0.5 on 2020-08-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_sociallinks_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
